### ISSUE TITLE
Agency login

### ISSUE THREAD

**Issue by falkenbach** [Altinn/ec-client-dotnet#1]
How it can be created at altinn website or how to apply for it? Can not find any references in official docs, assigned all available roles to test user 20015001543 at tt02 but it makes no difference.
Is it separate login or separate role?
Also tried login "malikSystem" from Advanced Settings, also no luck with it.

**Comment by erlendoksvoll** [comment]
Agency logins consist of the serviceowner certificate (along with an apikey that has access to the serviceowner resource)

**Comment by erlendoksvoll** [comment]
I was a bit too quick and forgot about the soap services ... In order to use the soap webservices for agencies, the agency will have to order a password/username from our self service portal
